spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/defaultdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/defaultdb
