spring:
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/defaultdb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/defaultdb


tenants:
  tenantsData:
    tenant1:
      postgresConnection:
        url: jdbc:postgresql://localhost:5432/tenant1
        username: postgres
        password: secret

    tenant2:
      postgresConnection:
        url: jdbc:postgresql://localhost:5432/tenant2
        username: postgres
        password: secret
