openapi: 3.0.1
info:
  title: Welcome API
  description: A simple API that returns a welcome message.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /welcome:
    get:
      tags:
        - Welcome
      summary: Show welcome message
      operationId: showWelcomeMessage
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: Hussam
          required: true
          description: Name of the person to welcome
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WelcomeResponse'
  /customers/register:
    post:
      tags:
        - Customers
      summary: Register a new customer for a tenant
      operationId: registerCustomer
      parameters:
        - in: header
          name: X-Tenant-ID
          schema:
            type: string
            example: tenant1
          required: true
          description: The tenant identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterCustomerRequest'
      responses:
        '200':
          description: Successfully created customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'

components:
  schemas:
    WelcomeResponse:
      type: object
      properties:
        message:
          type: string
          example: Welcome, Hussam!

    RegisterCustomerRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Hussam

    CustomerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Hussam
